from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).parents[2]
path = ROOT / "tools" / "tsun_diagnostic_gui.py"
text = path.read_text(encoding="utf-8")

text = text.replace('        "update_disabled": "Vérification automatique des mises à jour désactivée.",\n', '        "update_disabled": "Vérification automatique des mises à jour désactivée.",\n        "update_available_manual": "Mise à jour v{version} disponible — téléchargez la dernière version.",\n', 1)
text = text.replace('        "update_disabled": "Automatic update check disabled.",\n', '        "update_disabled": "Automatic update check disabled.",\n        "update_available_manual": "Update v{version} available — download the latest version.",\n', 1)

old_start = '''    def _start_update_check(self) -> None:\n        """Start a visible, non-blocking update check after the window is shown."""\n        if (\n            os.name != "nt"\n            or not getattr(sys, "frozen", False)\n            or "--no-update" in sys.argv\n        ):\n            self.update_busy = False\n            self.update_status.set(self.t["update_disabled"])\n            self.update_label.configure(fg=_MUTED)\n            self._sync_run_button()\n            return\n\n        self.update_busy = True\n'''
new_start = '''    def _start_update_check(self) -> None:\n        """Start a visible, non-blocking update check after the window is shown."""\n        if "--no-update" in sys.argv:\n            self.update_busy = False\n            self.update_status.set(self.t["update_disabled"])\n            self.update_label.configure(fg=_MUTED)\n            self._sync_run_button()\n            return\n\n        self.update_busy = True\n'''
if old_start not in text:
    raise SystemExit("start update anchor not found")
text = text.replace(old_start, new_start, 1)

old_run = '''    def _run_update_check(self) -> None:\n        """Check, download and verify a Windows update while reporting progress."""\n        try:\n            manifest = tsun_dump.fetch_update_manifest()\n            update = tsun_dump.select_update_component(\n                manifest,\n                tsun_dump.UPDATE_COMPONENT_WINDOWS_GUI,\n                APP_VERSION,\n            )\n            embedded_dump_update = tsun_dump.select_update_component(\n                manifest,\n                tsun_dump.UPDATE_COMPONENT_DUMP,\n                tsun_dump.TOOL_VERSION,\n            )\n            if update is None and embedded_dump_update is not None:\n                update = tsun_dump.select_update_component(\n                    manifest,\n                    tsun_dump.UPDATE_COMPONENT_WINDOWS_GUI,\n                    "0.0.0",\n                )\n            if update is None:\n                self.events.put(("update_current",))\n                return\n\n            version = update["version"]\n            self.events.put(("update_downloading", version))\n            destination = Path(tempfile.gettempdir()) / (\n                f"TSUN-Local-Diagnostic-update-{version}-{os.getpid()}.exe"\n            )\n            tsun_dump.download_verified_update(update, destination)\n            self.events.put(("update_ready", destination, version))\n        except Exception as exc:\n            self.events.put(("update_failed", type(exc).__name__))\n'''
new_run = '''    def _run_update_check(self) -> None:\n        """Check updates visibly on every platform; self-update only on Windows EXE."""\n        try:\n            manifest = tsun_dump.fetch_update_manifest()\n            dump_update = tsun_dump.select_update_component(\n                manifest,\n                tsun_dump.UPDATE_COMPONENT_DUMP,\n                tsun_dump.TOOL_VERSION,\n            )\n\n            is_windows_exe = os.name == "nt" and getattr(sys, "frozen", False)\n            if not is_windows_exe:\n                if dump_update is None:\n                    self.events.put(("update_current",))\n                else:\n                    self.events.put(("update_available_manual", dump_update["version"]))\n                return\n\n            update = tsun_dump.select_update_component(\n                manifest,\n                tsun_dump.UPDATE_COMPONENT_WINDOWS_GUI,\n                APP_VERSION,\n            )\n            if update is None and dump_update is not None:\n                # The Windows EXE embeds tsun_dump.py: refresh the EXE whenever\n                # the embedded engine is older, even if the GUI version is unchanged.\n                update = tsun_dump.select_update_component(\n                    manifest,\n                    tsun_dump.UPDATE_COMPONENT_WINDOWS_GUI,\n                    "0.0.0",\n                )\n            if update is None:\n                self.events.put(("update_current",))\n                return\n\n            version = update["version"]\n            self.events.put(("update_downloading", version))\n            destination = Path(tempfile.gettempdir()) / (\n                f"TSUN-Local-Diagnostic-update-{version}-{os.getpid()}.exe"\n            )\n            tsun_dump.download_verified_update(update, destination)\n            self.events.put(("update_ready", destination, version))\n        except Exception as exc:\n            self.events.put(("update_failed", type(exc).__name__))\n'''
if old_run not in text:
    raise SystemExit("run update anchor not found")
text = text.replace(old_run, new_run, 1)

poll_anchor = '''                elif kind == "update_downloading":\n                    self.update_status.set(\n                        self.t["update_found"].format(version=str(event[1]))\n                    )\n                    self.update_label.configure(fg=_ACCENT)\n                elif kind == "update_ready":\n'''
poll_replacement = '''                elif kind == "update_downloading":\n                    self.update_status.set(\n                        self.t["update_found"].format(version=str(event[1]))\n                    )\n                    self.update_label.configure(fg=_ACCENT)\n                elif kind == "update_available_manual":\n                    self.update_busy = False\n                    self.update_status.set(\n                        self.t["update_available_manual"].format(version=str(event[1]))\n                    )\n                    self.update_label.configure(fg=_ACCENT)\n                    self._sync_run_button()\n                elif kind == "update_ready":\n'''
if poll_anchor not in text:
    raise SystemExit("poll event anchor not found")
text = text.replace(poll_anchor, poll_replacement, 1)

path.write_text(text, encoding="utf-8")
