# Copyright (C) 2026 Jean-Philippe TESTART (jptstar)
# SPDX-License-Identifier: GPL-3.0-or-later

"""Protocol-independent constants for TSUN Local."""

from datetime import timedelta

DOMAIN = "tsun_local"
PLATFORMS = ["binary_sensor", "button", "sensor"]

CONF_LOGGER_SN = "logger_sn"
CONF_DISCOVERY_NETWORK = "discovery_network"
CONF_PROTOCOL = "protocol"
CONF_SCAN_INTERVAL = "scan_interval"
CONF_ERROR_SCAN_INTERVAL = "error_scan_interval"
CONF_OFFLINE_SCAN_INTERVAL = "offline_scan_interval"
CONF_FAILURE_THRESHOLD = "failure_threshold"

DEFAULT_PORT = 8899
DEFAULT_SCAN_INTERVAL = 20
MIN_SCAN_INTERVAL = 10
MAX_SCAN_INTERVAL = 300
DEFAULT_ERROR_SCAN_INTERVAL = 20
MIN_ERROR_SCAN_INTERVAL = 10
MAX_ERROR_SCAN_INTERVAL = 300
DEFAULT_OFFLINE_SCAN_INTERVAL = 300
MIN_OFFLINE_SCAN_INTERVAL = 60
MAX_OFFLINE_SCAN_INTERVAL = 3600
DEFAULT_FAILURE_THRESHOLD = 3
MIN_FAILURE_THRESHOLD = 1
MAX_FAILURE_THRESHOLD = 20
DEFAULT_UPDATE_INTERVAL = timedelta(seconds=DEFAULT_SCAN_INTERVAL)

MANUFACTURER = "TSUN"
